# Generated by Django 5.1.7 on 2025-03-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('is_child', models.BooleanField(default=False)),
                ('has_child', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('RAC', 'RAC'), ('WAITLIST', 'Waitlist')], default='WAITLIST', max_length=10)),
                ('berth_type', models.CharField(blank=True, choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper')], max_length=15, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth_number', models.IntegerField(unique=True)),
                ('berth_type', models.CharField(choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper')], max_length=15)),
                ('is_occupied', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.ticket')),
            ],
        ),
    ]
