# Generated by Django 5.1.7 on 2025-03-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='berth_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='berth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.berth'),
        ),
    ]
