# Generated by Django 5.1.7 on 2025-03-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_berth_ticket_remove_ticket_berth_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='berth_number',
        ),
    ]
